# Exercícios 
### Aluno: Sávio Murillo Dias Bastos

In [2]:
import numpy as np

### Exercicio:
1. Crie um array numpy com valores partindo de 10 até 49
2. Crie uma matriz numpy de 2 por 2 preenchida com 1's
3. Crie uma matriz numpy 3 por 2 de floats preenchida com 1's
4. Crie uma matriz 4 por 4 de integers preenchida com 5's
5. Crie uma matriz identidade de 3 por 3
6. Crie um array numppy prrenchido 3 integers aleatórias entre 1 e 10


In [35]:
# exercicio 1
np.arange(10, 50, 1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [36]:
#exercicio 2
np.full((2,2), 1)

array([[1, 1],
       [1, 1]])

In [39]:
#exercicio 2
np.ones((2,2), dtype=int)

array([[1, 1],
       [1, 1]])

In [40]:
#exercicio 3
np.ones((3,2), dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [41]:
#exercicio 4
np.full((4,4), 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [43]:
#exercicio 5
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [61]:
#exercicio 6
np.random.randint(1, 11, 3)

array([ 1,  8, 10])

`a.shape` # Array dimensions

`len(a)` #Length of array

`b.ndim` # Number of array dimensions

`e.size` # Number of array elements

`b.dtype` #Data type of array elements

`b.dtype.name` #Name of data type

`b.astype(int)` #Convert an array to a different type

In [62]:
display(a,b,c)

array([1, 2, 3])

array([[1.4, 2. , 3. ],
       [4. , 5. , 6. ]])

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [69]:
print('Para array a:')
print('Formato do array:', a.shape)
print('Comprimento do array:', len(a))
print('Dimensão:', a.ndim)
print('Quantidade de elementos do array:', a.size)
print('Tipo:', a.dtype)
print()

print('Para array b:')
print('Formato do array:', b.shape)
print('Comprimento do array:', len(b))
print('Dimensão:', b.ndim)
print('Quantidade de elementos do array:', b.size)
print('Tipo:', b.dtype)
print()

print('Para array c:')
print('Formato do array:', c.shape)
print('Comprimento do array:', len(c))
print('Dimensão:', c.ndim)
print('Quantidade de elementos do array:', c.size)
print('Tipo:', c.dtype)

Para array a:
Formato do array: (3,)
Comprimento do array: 3
Dimensão: 1
Quantidade de elementos do array: 3
Tipo: int32

Para array b:
Formato do array: (2, 3)
Comprimento do array: 2
Dimensão: 2
Quantidade de elementos do array: 6
Tipo: float64

Para array c:
Formato do array: (2, 2, 3)
Comprimento do array: 2
Dimensão: 3
Quantidade de elementos do array: 12
Tipo: float64


### Exercício:
1. Dado o array X = np.array(['A','B','C','D','E'])
Mostre o último elemento
2. Mostre os primeiros 3 elementos
3. Mostre só os elementos do meio
4. Inverta a ordem do array
5. Mostre os elementos nas posições impar.
6. De acordo com a matriz, mostre a primeira linha X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
7. Mostre o primeiro elemento na primeira linha
8. Mostre a linha intermediária
9. Os primeiros 2 elementos das duas primeiras linhas
10. Os últimos 2 elementos das duas últimas linhas

In [86]:
X = np.array(['A','B','C','D','E'])

In [88]:
#exercicio 2
X[:3]

array(['A', 'B', 'C'], dtype='<U1')

In [89]:
#exercicio 3
X[1:4]

array(['B', 'C', 'D'], dtype='<U1')

In [90]:
#exercicio 4
X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

In [96]:
#exercicio 5
X[1::2]

array(['B', 'D'], dtype='<U1')

In [97]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]])

In [100]:
#EXERCICIO 6
X[0]

array([1, 2, 3, 4])

In [113]:
#EXERCICIO 8
meio = X.shape[0]//2
linha_meio = X[meio, :]
linha_meio

array([ 9, 10, 11, 12])

In [108]:
#EXERCICIO 9
X[0:2,0:2]

array([[1, 2],
       [5, 6]])

In [115]:
#Exercicio 10
X[-2:,-2:]

array([[11, 12],
       [15, 16]])

### Exercicios:
1. De acordo com o array X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])
faça a soma
2. Faça a média
3. Dada a matriz faça a soma das colunas X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
4. Faça a média das linhas
5. Dado o array X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])
Mostre o elemento de maior valor

In [128]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])

In [129]:
#exercicio 1
np.sum(X)

43

In [130]:
#exercicio 2
np.mean(X)

4.777777777777778

In [134]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]])

In [135]:
#exercicio 3
np.sum(X, axis=1)

array([10, 26, 42, 58])

In [136]:
#exercicio 4
np.mean(X, axis=1)

array([ 2.5,  6.5, 10.5, 14.5])

In [132]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

In [133]:
#exercicio 5
np.max(X)

10