### Aluno: Sávio Murillo Dias Bastos
### Disciplina: Técnicas de programação | Ada Tech

### Exercicios

1. Replace all occurrences of 3 with 10, arr = np.array([1, 2, 3,3,3,3,3, 4, 5])
2. Find common elements between the two arrays, arr1 = np.array([1, 2, 3, 4, 5]), arr2 = np.array([3, 4, 5, 6, 7])
3. Reshape the array into a 2x4 matrix, arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
4. Remove duplicate elements, arr = np.array([1, 2, 2, 3, 4, 4, 5, 6, 6])
5. Split the array into three sub-arrays, arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
6. Perform element-wise multiplication, arr1 = np.array([1, 2, 3, 4]), arr2 = np.array([5, 6, 7, 8])

In [1]:
import numpy as np

In [2]:
#exercicio 1
arr = np.array([1, 2, 3,3,3,3,3, 4, 5])
arr[arr == 3] = 10
arr

array([ 1,  2, 10, 10, 10, 10, 10,  4,  5])

In [3]:
#exercicio 2
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 4, 5, 6, 7])
np.intersect1d(arr1, arr2)

array([3, 4, 5])

In [4]:
#exercicio 3
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.reshape(arr, (2,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
#xercicio 4
arr = np.array([1, 2, 2, 3, 4, 4, 5, 6, 6])
np.unique(arr)

array([1, 2, 3, 4, 5, 6])

In [6]:
#exercicio 5
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
np.split(arr,[3,7])

[array([1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10])]

In [7]:
#exercicio 6
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
arr1 * arr2

array([ 5, 12, 21, 32])

--------------
**Bora praticar!**  
  
Transforme o csv **dados_artificiais**, que está na pasta **dados**, para um numpy array (matriz)

In [8]:
#altura | peso | sexo
dados = np.loadtxt('dados_artificiais.txt', skiprows=1, dtype=float, usecols=(1,2,3))
dados

array([[ 1.788811, 65.648102,  0.      ],
       [ 1.566784, 76.642768,  0.      ],
       [ 2.092193, 55.468185,  1.      ],
       [ 1.782471, 67.281997,  1.      ],
       [ 1.735767, 69.289008,  0.      ],
       [ 1.686975, 56.840051,  0.      ],
       [ 1.797105, 65.208973,  1.      ],
       [ 1.187349, 48.164764,  0.      ],
       [ 1.595891, 45.410648,  1.      ],
       [ 1.396282, 67.930113,  0.      ],
       [ 1.606148, 67.719604,  0.      ],
       [ 1.70759 , 45.609333,  0.      ],
       [ 1.735513, 64.845452,  0.      ],
       [ 1.672055, 39.705952,  1.      ],
       [ 1.723377, 50.05888 ,  1.      ],
       [ 1.684574, 56.545087,  1.      ],
       [ 1.733259, 37.512188,  0.      ],
       [ 1.7579  , 57.362422,  0.      ],
       [ 1.913338, 69.307246,  1.      ],
       [ 1.456048, 69.342337,  0.      ]])

Agora utilize esta matriz para calcular o IMC, utilizando a equação

```
IMC = peso / altura**2
```
e insira na nova tabela

In [9]:
imc = np.array([dados[i][1] / (dados[i][0]**2) for i in range(len(dados))])
imc

array([20.51602694, 31.22143968, 12.67186291, 21.17648757, 22.99754561,
       19.97271779, 20.19112211, 34.16431009, 17.8299961 , 34.8430415 ,
       26.25084498, 15.64179232, 21.52899612, 14.20216309, 16.85468124,
       19.92575058, 12.48663648, 18.5626146 , 18.93194561, 32.70748042])

In [10]:
dados_imc = np.column_stack((dados, imc))
dados_imc

array([[ 1.788811  , 65.648102  ,  0.        , 20.51602694],
       [ 1.566784  , 76.642768  ,  0.        , 31.22143968],
       [ 2.092193  , 55.468185  ,  1.        , 12.67186291],
       [ 1.782471  , 67.281997  ,  1.        , 21.17648757],
       [ 1.735767  , 69.289008  ,  0.        , 22.99754561],
       [ 1.686975  , 56.840051  ,  0.        , 19.97271779],
       [ 1.797105  , 65.208973  ,  1.        , 20.19112211],
       [ 1.187349  , 48.164764  ,  0.        , 34.16431009],
       [ 1.595891  , 45.410648  ,  1.        , 17.8299961 ],
       [ 1.396282  , 67.930113  ,  0.        , 34.8430415 ],
       [ 1.606148  , 67.719604  ,  0.        , 26.25084498],
       [ 1.70759   , 45.609333  ,  0.        , 15.64179232],
       [ 1.735513  , 64.845452  ,  0.        , 21.52899612],
       [ 1.672055  , 39.705952  ,  1.        , 14.20216309],
       [ 1.723377  , 50.05888   ,  1.        , 16.85468124],
       [ 1.684574  , 56.545087  ,  1.        , 19.92575058],
       [ 1.733259  , 37.

| IMC             | Categoria           |   |
|-----------------|---------------------|---|
| abaixo de 16,00 | Baixo peso Grau III |   |
| 16,00 a 16,99   | Baixo peso Grau II  |   |
| 17,00 a 18.49   | Baixo peso Grau I   |   |
| 18,50 a 24,99   | Peso ideal          |   |
| 25,00 a 29,99   | Sobrepeso           |   |
| 30,00 a 34,99   | Obesidade Grau I    |   |
| 35,00 a 39,99   | Obesidade Grau II   |   |
| 40,0 e acima    | Obesidade Grau III  |   |

Agora utilize a tabela acima para indicar a qual categoria cada valor de IMC se enquadra. Insira novamente na tabela.

In [11]:
imc = dados_imc[:,-1]

def classificar_imc(imc):
    categorias = [
        ("Baixo peso Grau III", lambda x: x < 16.00),
        ("Baixo peso Grau II", lambda x: 16.00 <= x <= 16.99),
        ("Baixo peso Grau I", lambda x: 17.00 <= x <= 18.49),
        ("Peso ideal", lambda x: 18.50 <= x <= 24.99),
        ("Sobrepeso", lambda x: 25.00 <= x <= 29.99),
        ("Obesidade Grau I", lambda x: 30.00 <= x <= 34.99),
        ("Obesidade Grau II", lambda x: 35.00 <= x <= 39.99),
        ("Obesidade Grau III", lambda x: x >= 40.0)
    ]

    resultados = []
    for valor in imc:
        for categoria, condicao in categorias:
            if condicao(valor):
                resultados.append((valor, categoria))
                

    return np.array(resultados)

class_imc = classificar_imc(imc)
dados_imc = np.column_stack([dados_imc.astype(str), class_imc[:,1]])


In [12]:
dados_imc

array([['1.788811', '65.648102', '0.0', '20.516026942563006',
        'Peso ideal'],
       ['1.566784', '76.642768', '0.0', '31.221439684559105',
        'Obesidade Grau I'],
       ['2.092193', '55.468185', '1.0', '12.671862911844382',
        'Baixo peso Grau III'],
       ['1.782471', '67.281997', '1.0', '21.176487571306087',
        'Peso ideal'],
       ['1.735767', '69.289008', '0.0', '22.9975456097574', 'Peso ideal'],
       ['1.686975', '56.840051', '0.0', '19.972717793575036',
        'Peso ideal'],
       ['1.797105', '65.208973', '1.0', '20.191122114932906',
        'Peso ideal'],
       ['1.187349', '48.164764', '0.0', '34.16431008742802',
        'Obesidade Grau I'],
       ['1.595891', '45.410648', '1.0', '17.829996098895624',
        'Baixo peso Grau I'],
       ['1.396282', '67.930113', '0.0', '34.84304150287812',
        'Obesidade Grau I'],
       ['1.606148', '67.719604', '0.0', '26.250844980187235',
        'Sobrepeso'],
       ['1.70759', '45.609333', '0.0', '15.6

### criar a tabela e salvar o txt

In [13]:
dados_num = dados_imc[:, :4].astype(float)
dados_imc_final = np.column_stack((dados_num, dados_imc[:, 4]))

np.savetxt("dados_imc.txt", dados_imc_final, delimiter=' ', fmt='%s', header="altura  |  peso  |  sexo  |  imc  |  classificacao_imc")